# Generated by Django 3.1.7 on 2021-05-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
    ]
