# Generated by Django 3.1.7 on 2021-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_administrator_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
