# Generated by Django 3.1.7 on 2021-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210428_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.DeleteModel(
            name='Ale',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Mensaje enviado'),
            preserve_default=False,
        ),
    ]
