# Generated by Django 3.2.6 on 2021-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_generalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Configuración'),
        ),
    ]
