# Generated by Django 3.2.6 on 2021-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_generalconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='tournament_sensitive',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Sensibilidad a fecha de torneo'),
        ),
    ]
