# Generated by Django 3.1.7 on 2021-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('win', models.PositiveIntegerField(verbose_name='Partidos Ganados')),
                ('drawn', models.PositiveIntegerField(verbose_name='Partidos Empatados')),
                ('lost', models.PositiveIntegerField(verbose_name='Partidos Perdidos')),
                ('titles', models.PositiveIntegerField(verbose_name='Títulos conseguidos')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Habilitado')),
                ('status', models.BooleanField(verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
