# Generated by Django 3.1.7 on 2021-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210727_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank='True', default='teams/default/1.png', null=True, upload_to='teams/%y/%m', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Estado'),
        ),
    ]
