# Generated by Django 3.1.13 on 2021-08-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20210802_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre y Apellido')),
                ('dni', models.PositiveIntegerField(verbose_name='DNI')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('date_born', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('goals', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Goles')),
                ('assists', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Asistencias')),
                ('yellow_cards', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Tarjetas Amarillas')),
                ('red_cards', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Tarjetas Rojas')),
                ('played', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Partidos Jugados')),
                ('status', models.BooleanField(blank=True, default=True, verbose_name='Estado')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Strickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
            options={
                'verbose_name': 'Delantero',
                'verbose_name_plural': 'Delanteros',
            },
        ),
        migrations.CreateModel(
            name='Middle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
            options={
                'verbose_name': 'Mediocampista',
                'verbose_name_plural': 'Mediocampistas',
            },
        ),
        migrations.CreateModel(
            name='Goalkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_invict', models.PositiveSmallIntegerField(verbose_name='Valla invictas')),
                ('goals_recibed', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
            options={
                'verbose_name': 'Arquero',
                'verbose_name_plural': 'Arqueros',
            },
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
            options={
                'verbose_name': 'Defensor',
                'verbose_name_plural': 'Defensores',
            },
        ),
    ]
