# Generated by Django 3.1.13 on 2021-08-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_defense_goalkeeper_middle_player_strickers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('teams', models.PositiveSmallIntegerField(verbose_name='Cantidad de equipos')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('date_init', models.DateField(blank=True, null=True, verbose_name='Fecha de comienzo')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.CreateModel(
            name='PlayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_round', models.PositiveSmallIntegerField(verbose_name='Rondas')),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('torunament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
            options={
                'verbose_name': 'Eliminatoria',
                'verbose_name_plural': 'Eliminatorias',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_local', models.PositiveSmallIntegerField(verbose_name='Goles equipo local')),
                ('goals_away', models.PositiveSmallIntegerField(verbose_name='Goles equipo visitante')),
                ('date_of_match', models.DateTimeField(verbose_name='Fecha del partido')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitante', to='team.team', verbose_name='Equipo visitante')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.fieldmatch')),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local', to='team.team', verbose_name='Equipo local')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchs', models.PositiveSmallIntegerField(verbose_name='Partidos')),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
    ]
