# Generated by Django 3.1.13 on 2021-08-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_fieldmatch_league_match_playoff_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre y Apellido'),
        ),
    ]
