# Generated by Django 3.2.6 on 2021-08-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20210803_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(blank=True, choices=[('1', 'Liga'), ('2', 'Eliminatoria'), ('3', 'Grupo y Eliminatoria'), ('4', 'Zonas')], default='1', max_length=1, null=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización de inscripción'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre del torneo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado'),
        ),
    ]
