# Generated by Django 3.2.6 on 2021-08-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20210818_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='matchs',
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(related_name='league_teams', to='team.Team'),
        ),
        migrations.CreateModel(
            name='TeamLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
