# Generated by Django 3.2.6 on 2021-08-18 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_noticia'),
        ('team', '0013_auto_20210818_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='delegated',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.administrator'),
        ),
    ]
