# Generated by Django 3.2.6 on 2021-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20210818_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dni',
            field=models.PositiveIntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
