# Generated by Django 3.2.6 on 2021-08-18 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_alter_player_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Posición')),
                ('played', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos jugados')),
                ('wins', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos ganados')),
                ('loss', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos perdidos')),
                ('draw', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos empatados')),
                ('goals', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles')),
                ('goals_received', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles Recibidos')),
                ('dif_goals', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Diferencia de goles')),
                ('points', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Puntos')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.league')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
            ],
            options={
                'verbose_name': 'Tabla de Posiciones',
                'verbose_name_plural': 'Tabla de Posiciones',
                'ordering': ['-points'],
            },
        ),
    ]
