# Generated by Django 3.2.6 on 2021-08-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Habilitado'),
        ),
    ]
