# Generated by Django 3.2.6 on 2021-08-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_alter_team_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fecha Jugada'),
        ),
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Partidos Ganados'),
        ),
        migrations.AlterField(
            model_name='team',
            name='drawn',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Partidos Empatados'),
        ),
        migrations.AlterField(
            model_name='team',
            name='lost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Partidos Perdidos'),
        ),
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Títulos conseguidos'),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Partidos Ganados'),
        ),
    ]
