# Generated by Django 3.2.6 on 2021-08-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0022_auto_20210823_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='vueltas',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Vueltas'),
        ),
    ]
