# Generated by Django 3.2.6 on 2021-08-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0024_auto_20210824_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
