# Generated by Django 3.2.6 on 2021-08-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0025_alter_leaguetable_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.league'),
        ),
    ]
