# Generated by Django 3.2.6 on 2021-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0026_alter_leaguetable_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='dif_goals',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Diferencia de goles'),
        ),
    ]
