# Generated by Django 3.2.6 on 2021-08-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_alter_leaguetable_dif_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='drawn',
            new_name='draw',
        ),
        migrations.CreateModel(
            name='Scorers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Posición')),
                ('goals', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles')),
                ('played', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos Jugados')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
            options={
                'verbose_name': 'Tabla de Goleadores',
                'verbose_name_plural': 'Tabla de Goleadores',
            },
        ),
    ]
