# Generated by Django 3.2.6 on 2021-08-26 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0028_auto_20210825_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Posición')),
                ('played', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos Jugados')),
                ('yellow_cards', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Tarjetas Amarillas')),
                ('red_cards', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Tarjetas Rojas')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
            options={
                'verbose_name': 'Tabla de Amonestados',
                'verbose_name_plural': 'Tabla de Amonestados',
            },
        ),
    ]
