# Generated by Django 3.2.6 on 2021-08-27 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0030_dateofmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Dia de la semana')),
            ],
            options={
                'verbose_name': 'Día de la semana',
                'verbose_name_plural': 'Dias de la semana',
            },
        ),
        migrations.CreateModel(
            name='ConfigTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_init', models.CharField(choices=[('00', '00:00'), ('01', '01:00'), ('02', '02:00'), ('03', '03:00'), ('04', '04:00'), ('05', '05:00'), ('06', '06:00'), ('07', '07:00'), ('08', '08:00'), ('09', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00'), ('21', '21:00'), ('22', '22:00'), ('23', '23:00')], max_length=2, verbose_name='Horario de comienzo de los partidos')),
                ('hour_end', models.CharField(choices=[('00', '00:00'), ('01', '01:00'), ('02', '02:00'), ('03', '03:00'), ('04', '04:00'), ('05', '05:00'), ('06', '06:00'), ('07', '07:00'), ('08', '08:00'), ('09', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00'), ('21', '21:00'), ('22', '22:00'), ('23', '23:00')], max_length=2, verbose_name='Horario de finalización de los partidos')),
                ('days', models.ManyToManyField(to='team.DaysOfWeek')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.tournament')),
            ],
            options={
                'verbose_name': 'Configuración del Torneo',
                'verbose_name_plural': 'Configuraciones de Torneos',
            },
        ),
    ]
