# Generated by Django 3.2.6 on 2021-08-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0031_configtournament_daysofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtournament',
            name='days',
            field=models.ManyToManyField(to='team.DaysOfWeek', verbose_name='Dias en los que se juegan los partidos'),
        ),
    ]
