# Generated by Django 3.2.6 on 2021-08-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0032_alter_configtournament_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtournament',
            name='fields',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de canchas disponibles para jugar'),
        ),
    ]
