# Generated by Django 3.2.6 on 2021-08-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0033_configtournament_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmatch',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.tournament'),
        ),
    ]
