# Generated by Django 3.2.6 on 2021-08-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0034_fieldmatch_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateofmatch',
            name='played',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fecha Jugada'),
        ),
    ]
