# Generated by Django 3.2.6 on 2021-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0035_dateofmatch_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateofmatch',
            name='day_of_match',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Juego'),
        ),
        migrations.AlterField(
            model_name='dateofmatch',
            name='matchs',
            field=models.ManyToManyField(blank=True, null=True, to='team.Match'),
        ),
        migrations.AlterField(
            model_name='dateofmatch',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de Fecha'),
        ),
    ]
