# Generated by Django 3.2.6 on 2021-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0036_auto_20210827_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals_away',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles equipo visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_local',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles equipo local'),
        ),
        migrations.AlterField(
            model_name='match',
            name='played',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Partido Jugado'),
        ),
    ]
