# Generated by Django 3.2.6 on 2021-08-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0037_auto_20210827_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.fieldmatch', verbose_name='Cancha'),
        ),
    ]
