# Generated by Django 3.2.6 on 2021-08-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0038_alter_match_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals_away',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles equipo visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_local',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles equipo local'),
        ),
    ]
