# Generated by Django 3.2.6 on 2021-08-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0040_alter_configtournament_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dorsal',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Dorsal'),
        ),
    ]
