# Generated by Django 3.2.6 on 2021-09-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0042_groupandplayoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Nombre del Grupo')),
                ('group_play_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.groupandplayoff')),
                ('teams', models.ManyToManyField(to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Posición')),
                ('played', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos jugados')),
                ('wins', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos ganados')),
                ('loss', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos perdidos')),
                ('draw', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Partidos empatados')),
                ('goals', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles')),
                ('goals_received', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles Recibidos')),
                ('dif_goals', models.IntegerField(blank=True, default=0, null=True, verbose_name='Diferencia de goles')),
                ('points', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Puntos')),
                ('group_play_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
