# Generated by Django 3.2.6 on 2021-10-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0046_remove_cautions_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Penales Visitante'),
        ),
        migrations.AddField(
            model_name='match',
            name='local_penalties',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Penales Local'),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Penales'),
        ),
    ]
