# Generated by Django 3.2.6 on 2021-10-11 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0047_auto_20211003_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateofmatch',
            options={'verbose_name': 'Fecha', 'verbose_name_plural': 'Fechas'},
        ),
    ]
