# Generated by Django 3.2.6 on 2021-10-17 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0048_alter_dateofmatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_amonestated', models.CharField(choices=[('1', 'Amonestación Simple'), ('2', 'Doble Amarilla'), ('3', 'Roja Directa')], default='1', max_length=1, verbose_name='Tipo de amonestación')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player', verbose_name='Jugador')),
            ],
        ),
    ]
